sudo: required
dist: trusty
language: c
compiler:
  - gcc

git:
  depth: 5

env:
  matrix:
    - PG=9.5 LUAV=lua-5.3.5
    - PG=9.6 LUAV=lua-5.3.5
    - PG=10  LUAV=lua-5.3.5
    - PG=10  LUAV=LuaJIT-b025b01
    - PG=11  LUAV=lua-5.3.5
    - PG=12  LUAV=lua-5.3.5

addons:
  apt:
    sources:
    - sourceline: "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 12"
      key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"

before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo apt-get update
  - sudo rm -rf /var/lib/postgresql
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-${PG:?} postgresql-contrib-${PG:?} postgresql-server-dev-${PG:?}
  - |
    mkdir "$LUAV"
    if [[ "$LUAV" == lua-* ]]; then
      LUA_URL="http://www.lua.org/ftp/"
      if [[ "$LUAV" == *-work* ]]; then
        LUA_URL="http://www.lua.org/work/"
      fi
      wget -O- "${LUA_URL}${LUAV}".tar.gz \
        | tar zx --strip-components=1 -C "$LUAV"
      make -C "$LUAV"/src \
        SYSCFLAGS="-DLUA_USE_POSIX -DLUA_USE_DLOPEN -ULUA_COMPAT_5_2" \
        SYSLIBS="-Wl,-E -ldl" \
        MYCFLAGS="-fPIC" liblua.a lua luac
      export LUAC="$PWD/$LUAV/src/luac"
      export LUA="$PWD/$LUAV/src/lua"
    elif [[ "$LUAV" == LuaJIT-* ]]; then
      wget -O- https://github.com/LuaJIT/LuaJIT/archive/"${LUAV#LuaJIT-}".tar.gz \
        | tar zx --strip-components=1 -C "$LUAV"
      make -C "$LUAV"/src \
        XCFLAGS="-DLUAJIT_ENABLE_GC64 -DLUAJIT_ENABLE_LUA52COMPAT" \
        CFLAGS="-fPIC -O3" libluajit.a luajit
      export LUAJIT="$PWD/$LUAV/src/luajit"
      export LUAJITC="cp"
    fi
    export LUA_INCDIR="$PWD/$LUAV/src"
    mv $LUAV/src/liblua*.a ./libcurrent_lua_build.a
    export LUALIB="-L$PWD -lcurrent_lua_build"

before_script:
  - sudo -u postgres createuser -s "$USER"

script:
  - |
    make && sudo make install && time make installcheck &&
        if [ -z "$NO_HSTORE" ]; then
            make -C hstore && sudo make -C hstore install && time make -C hstore installcheck
        fi

after_script:
  - |
    cat regression.diffs || true
    cat hstore/regression.diffs || true

